### ISSUE TITLE
Admin 'Users' button

### ISSUE THREAD

**Issue by Lme999** [fbatroni/passwordmanager#72]
**Describe the bug**
Displays the wrong screen.

**To Reproduce**
Create admin account.
Log out.
Create second normal user account.
Log out, and log back into admin account.
Click on 'Users' button. (It will display the password credential screen instead of user screen)

**Expected behavior**
Should show other users like on initial first login for the admin.

**Comment by Lme999** [comment]
This happens when the 'admin' user logs in using the email address.
When the 'admin' user logs in using their username it works as intended.

**Comment by Aceness802** [comment]
It would seem there's something going wrong with the user session. There is a logout function present to clear the current user who was logged in when "Logout" is clicked. It seems it's able to detect the admin user is an admin to display the button, but it's not letting the screen display because it can't tell the use is an admin elsewhere.

**Comment by fbatroni** [comment]
fixed
